// Code generated by protoc-gen-go. DO NOT EDIT.
// source: flowfabric.proto

package ff

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// CaputreInfo containing network details
type CaptureInfo struct {
	Src                  string   `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dst                  string   `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`
	Stop                 bool     `protobuf:"varint,3,opt,name=stop,proto3" json:"stop,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CaptureInfo) Reset()         { *m = CaptureInfo{} }
func (m *CaptureInfo) String() string { return proto.CompactTextString(m) }
func (*CaptureInfo) ProtoMessage()    {}
func (*CaptureInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f228048f95a44b08, []int{0}
}

func (m *CaptureInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CaptureInfo.Unmarshal(m, b)
}
func (m *CaptureInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CaptureInfo.Marshal(b, m, deterministic)
}
func (m *CaptureInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CaptureInfo.Merge(m, src)
}
func (m *CaptureInfo) XXX_Size() int {
	return xxx_messageInfo_CaptureInfo.Size(m)
}
func (m *CaptureInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CaptureInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CaptureInfo proto.InternalMessageInfo

func (m *CaptureInfo) GetSrc() string {
	if m != nil {
		return m.Src
	}
	return ""
}

func (m *CaptureInfo) GetDst() string {
	if m != nil {
		return m.Dst
	}
	return ""
}

func (m *CaptureInfo) GetStop() bool {
	if m != nil {
		return m.Stop
	}
	return false
}

func init() {
	proto.RegisterType((*CaptureInfo)(nil), "ff.CaptureInfo")
}

func init() { proto.RegisterFile("flowfabric.proto", fileDescriptor_f228048f95a44b08) }

var fileDescriptor_f228048f95a44b08 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xcb, 0xc9, 0x2f,
	0x4f, 0x4b, 0x4c, 0x2a, 0xca, 0x4c, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4a, 0x4b,
	0x53, 0x72, 0xe5, 0xe2, 0x76, 0x4e, 0x2c, 0x28, 0x29, 0x2d, 0x4a, 0xf5, 0xcc, 0x4b, 0xcb, 0x17,
	0x12, 0xe0, 0x62, 0x2e, 0x2e, 0x4a, 0x96, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x41,
	0x22, 0x29, 0xc5, 0x25, 0x12, 0x4c, 0x10, 0x91, 0x94, 0xe2, 0x12, 0x21, 0x21, 0x2e, 0x96, 0xe2,
	0x92, 0xfc, 0x02, 0x09, 0x66, 0x05, 0x46, 0x0d, 0x8e, 0x20, 0x30, 0xdb, 0xc8, 0x99, 0x8b, 0xcf,
	0x2f, 0xb5, 0xa4, 0x3c, 0xbf, 0x28, 0x1b, 0x6a, 0x9a, 0x90, 0x21, 0x17, 0x3b, 0x8c, 0xc9, 0xaf,
	0x97, 0x96, 0xa6, 0x87, 0x64, 0x8b, 0x14, 0xba, 0x80, 0x12, 0x83, 0x06, 0xa3, 0x01, 0x63, 0x12,
	0x1b, 0xd8, 0x59, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9f, 0xe7, 0x5c, 0xf0, 0xaa, 0x00,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NetworkCaptureClient is the client API for NetworkCapture service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NetworkCaptureClient interface {
	// Capture captures network
	Capture(ctx context.Context, opts ...grpc.CallOption) (NetworkCapture_CaptureClient, error)
}

type networkCaptureClient struct {
	cc *grpc.ClientConn
}

func NewNetworkCaptureClient(cc *grpc.ClientConn) NetworkCaptureClient {
	return &networkCaptureClient{cc}
}

func (c *networkCaptureClient) Capture(ctx context.Context, opts ...grpc.CallOption) (NetworkCapture_CaptureClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NetworkCapture_serviceDesc.Streams[0], "/ff.NetworkCapture/Capture", opts...)
	if err != nil {
		return nil, err
	}
	x := &networkCaptureCaptureClient{stream}
	return x, nil
}

type NetworkCapture_CaptureClient interface {
	Send(*CaptureInfo) error
	Recv() (*CaptureInfo, error)
	grpc.ClientStream
}

type networkCaptureCaptureClient struct {
	grpc.ClientStream
}

func (x *networkCaptureCaptureClient) Send(m *CaptureInfo) error {
	return x.ClientStream.SendMsg(m)
}

func (x *networkCaptureCaptureClient) Recv() (*CaptureInfo, error) {
	m := new(CaptureInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NetworkCaptureServer is the server API for NetworkCapture service.
type NetworkCaptureServer interface {
	// Capture captures network
	Capture(NetworkCapture_CaptureServer) error
}

// UnimplementedNetworkCaptureServer can be embedded to have forward compatible implementations.
type UnimplementedNetworkCaptureServer struct {
}

func (*UnimplementedNetworkCaptureServer) Capture(srv NetworkCapture_CaptureServer) error {
	return status.Errorf(codes.Unimplemented, "method Capture not implemented")
}

func RegisterNetworkCaptureServer(s *grpc.Server, srv NetworkCaptureServer) {
	s.RegisterService(&_NetworkCapture_serviceDesc, srv)
}

func _NetworkCapture_Capture_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NetworkCaptureServer).Capture(&networkCaptureCaptureServer{stream})
}

type NetworkCapture_CaptureServer interface {
	Send(*CaptureInfo) error
	Recv() (*CaptureInfo, error)
	grpc.ServerStream
}

type networkCaptureCaptureServer struct {
	grpc.ServerStream
}

func (x *networkCaptureCaptureServer) Send(m *CaptureInfo) error {
	return x.ServerStream.SendMsg(m)
}

func (x *networkCaptureCaptureServer) Recv() (*CaptureInfo, error) {
	m := new(CaptureInfo)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _NetworkCapture_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ff.NetworkCapture",
	HandlerType: (*NetworkCaptureServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Capture",
			Handler:       _NetworkCapture_Capture_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "flowfabric.proto",
}
